#!/bin/bash
echo "=== Testing Logging Setup ==="
echo ""
echo "1. Checking if containers are running..."
docker ps --filter "name=countries-api" --filter "name=loki" --filter "name=promtail" --filter "name=grafana" --format "table {{.Names}}\t{{.Status}}"
echo ""
echo "2. Checking Promtail logs..."
docker logs promtail --tail 20
echo ""
echo "3. Checking Loki is receiving logs..."
curl -s "http://localhost:3100/ready" && echo " - Loki is ready"
echo ""
echo "4. Querying Loki for recent logs..."
curl -s -G "http://localhost:3100/loki/api/v1/query_range" --data-urlencode 'query={service="countries-api"}' --data-urlencode 'limit=5' | jq '.data.result[] | .stream' 2>/dev/null || echo "No logs found or jq not installed"
echo ""
echo "5. Making a test request to generate logs..."
curl -s http://localhost:3000/country > /dev/null && echo "Request sent"
echo ""
echo "=== Done ==="
